### ISSUE TITLE
demand

### ISSUE THREAD

**Issue by sixgodfan** [Tak-Pesar/Tron#2]
Account multi-signature, account permission modification: how to put an account completely managed by another account, request to write a demo, thanks (machine translation)

**Comment by sixgodfan** [comment]
Fatal error: Uncaught TypeError: Tak\Tron\API::getAccount(): Return value must be of type object, string returned in H:\phpEnv\www\localhost\vendor\takpesar\tron\src\API.php:235 Stack trace: #0 H:\phpEnv\www\localhost\vendor\takpesar\tron\src\API.php(256): Tak\Tron\API->getAccount('415e457c466ac62...') #1 H:\phpEnv\www\localhost\a.php(14): Tak\Tron\API->getBalance() #2 {main} thrown in H:\phpEnv\www\localhost\vendor\takpesar\tron\src\API.php on line 235

**Comment by Tak-Pesar** [comment]
When does this happen ?

**Comment by sixgodfan** [comment]
When getting the balance

**Comment by sixgodfan** [comment]
```
<?php
require_once "./vendor/autoload.php";
use Tak\Tron\API;

$tron = new API();
$tron->setWallet('TJZfm2PSQ38WNwzPqSBpTbVAynZpMEmfKR');
$balance = $tron->getBalance();
print 'your balance  : '.$balance;

### Then it reported an error, did I write it incorrectly?
```

**Comment by Tak-Pesar** [comment]
Well, your problem is connecting and sending a request to TronAPI
And I made it not return the error as a string and it throw that error and you can catch it
Just try this :

```php
$tron = new API();
$tron->setWallet('TJZfm2PSQ38WNwzPqSBpTbVAynZpMEmfKR');
try {
    $balance = $tron->getBalance();
    print 'your balance  : '.$balance;
} catch(\Throwable $error){
    print $error->getMessage();
}
```

**Comment by sixgodfan** [comment]
Latest version and use your code above to get alerts on balance:
Tak\Tron\API::getAccount(): Return value must be of type object, string returned

**Comment by Tak-Pesar** [comment]
Now it gives another error install the latest version please

commit : https://github.com/Tak-Pesar/Tron/commit/fb21bf887fbf7147c2f374654e057a4bfc862bd4

**Comment by sixgodfan** [comment]
Thanks, it is already working fine to get the trx balance. How to get the balance of usdt (TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t) please, write an example, thanks!

**Comment by Tak-Pesar** [comment]
You have to calculate yourself based on the price of Tron cryptocurrency. Unfortunately, this does not apply to our library
